# Python Programming:  Simple Random Sampling


## Importing our Libraries

In [ ]:
# importing numpy
import numpy as np

# importing pandas
import pandas as pd

# importing random module
# we will use random.sample() function to return a k length 
# list of unique elements chosen from our population
import random

## 1.0 Selecting More than One item from a List

In [ ]:
# Example 1
# ---
# Selecting more than one item from a list 
# ---
#

list = [20, 40, 80, 100, 120]
print ("Choosing 3 random items from a list using sample function", random.sample(list, k=3))

list = [20, 40, 20, 20, 20]
print ("Choosing 3 random items from a list using sample function",random.sample(list, k=3))

# As you can see we pass k=3 to choose 3 random elements from a list. 
# In return, we got a list of 3 random items.

Choosing 3 random items from a list using sample function [120, 100, 80]
Choosing 3 random items from a list using sample function [40, 20, 20]


### <font color="green"> 1.0 Challenges</font>

In [ ]:
# Challenge 1
# ---
# Question: Create a list containing 10 counties in Kenya 
# then select 2 random counties from the list.
# ---
# 
counties = ['Nyandarua','Kiambu','Mombasa','Nyeri']
print('counties include:', random.sample(counties, k=2))

counties include: ['Nyandarua', 'Kiambu']


## 2.0  Selecting the Random Sample from Dictionary

In [ ]:
# Example 1
# ---
# We can select a random key-value pair from the dictionary as shown 
# ---
#
marks_dict = {
  "Kelly": 55,
  "jhon": 70,
  "Donald": 60,
  "Lennin" :50
}

print ("Choosing 2 random items from a dictionary using sample method ", random.sample(marks_dict.items(), k=2))

Choosing 2 random items from a dictionary using sample method  [('Kelly', 55), ('jhon', 70)]


### <font color="green">2.0 Challenges</font>

In [ ]:
# Challenge 1
# ---
# A caterer offers three different food packages; 
# bronze package: starch:rice stew:chicken curry vegetable:cabbages desert:melon
# silver package: starch:rice and chappati  stew:beef curry vegetable:spinach desert:melon and bananas
# gold package: starch:rice, chappati and mukimo stew: beef curry vegetable:spinach and managu desert: tart
# Create a dictionary that stores the above information and select a sample of size 2 
# ---
#
bronze_package = {
    'starch':'rice',
    'stew':'chicken',
    'curry vegetable':'cabbages',
    'desert':'melon'
}
silver_package = {
    'starch':'rice and chappati', 
    'stew':'beef',
    'curry vegetable':'spinach',
    'desert':'melon and bananas'
}
gold_package = {
    'starch':'rice, chappati and mukimo',
    'stew':'beef',
    'curry vegetable':'spinach and managu', 
    'desert': 'tart'
}
print ("bronze_package: ", random.sample(bronze_package.items(), k=2))
print ("silver_package: ", random.sample(silver_package.items(), k=2))
print ("gold_package: ", random.sample(gold_package.items(), k=2))

bronze_package:  [('curry vegetable', 'cabbages'), ('desert', 'melon')]
silver_package:  [('desert', 'melon and bananas'), ('stew', 'beef')]
gold_package:  [('stew', 'beef'), ('desert', 'tart')]


## 3.0 Selecting a Random Sample with Replacement to including repetition


In [ ]:
# Example 1
# ---
# We can select a random sample with replacement to include repetition as shown below
# ---
# 
names = ["Roger", "Nadal", "Novac", "Andre", "Sarena", "Mariya", "Martina"]

print("random sample with replacement to including repetition ", random.choices(names, k=3))

random sample with replacement to including repetition  ['Roger', 'Sarena', 'Sarena']


### <font color="green">3.0 Challenges</font>

In [ ]:
# Challenge 1
# ---
# Question: Select a random sample of 3 with replacement to include replacement from the 
# following list of months
# ---
#

months = ['January', 'February', 'March', 'April', 'May', 'June', 'July',
          'August', 'September', 'October', 'November', 'December']

print ("Months: ", random.choices(months, k=3))

Months:  ['April', 'August', 'August']


## 4.0 Selecting a Random Sample from a Range of Integers

In [ ]:
# Example 1
# ---
# We can select a random sample from a range of integers as shown below
# ---
# 

weight_set = {40, 50, 55, 65, 75, 80}

print ("Choosing 4 random items from a set ", random.sample(weight_set, k=4))

Choosing 4 random items from a set  [55, 40, 50, 65]


### <font color="green">4.1 Challenges</font>

In [ ]:
# Challenge 1
# ---
# Question: Select a random sample from a range of integers as shown below
# --- 
# 
weight_set = {4, 5, 6, 7, 8, 9, 10}

print("weight:", random.sample(weight_set, k=3))

weight: [7, 9, 10]


## 5.0 Selecting a Sample Array from a Large multidimensional Array



In [ ]:
# Example 1
# ---
# We can select a sample array from a large multidimensional array as shown
# ---
# 

array = np.array([[2 ,4, 6], [5, 10, 15], [6, 12, 18], [7, 14, 21], [8, 16, 24]]) 
print("Printing 2D Array")
print(array)

# selecting multiple random rows from the 2D as shown
print("Selecting multiple random rows from the 2D array")
randomRows = np.random.randint(5, size=2)
for i in randomRows:
  print(array[i,:])

Printing 2D Array
[[ 2  4  6]
 [ 5 10 15]
 [ 6 12 18]
 [ 7 14 21]
 [ 8 16 24]]
Selecting multiple random rows from the 2D array
[ 8 16 24]
[2 4 6]


### <font color="green">5.0 Challenges</font>

In [ ]:
# Challenge 1
# ---
# Question: Select two arrays from the given multidimensional array
# ---
# 

a = np.array([[2, 4, 6, 8, 10], [3, 6, 9, 12, 15], [4, 8, 12, 16, 20], [1 ,2 , 4, 5, 6], [5, 10, 15, 20, 25], [6, 12, 18, 24, 30], [7, 14, 21, 28, 35]])  
randomRow = np.random.randint(7, size=2)
for i in randomRow:
  print(a[i,:])

[ 3  6  9 12 15]
[1 2 4 5 6]


## 6.0 Selecting Random Samples from a Dataset

In [ ]:
# Example 1
# ---
# Selecting a random sample from the following medical appointments dataset
# ---
# Dataset url = http://bit.ly/MedicalAppointmentsDataset
# ---
# 

# Loading the dataset
medical_df = pd.read_csv("http://bit.ly/MedicalAppointmentsDataset")

# Determining the size
print(medical_df.shape)


# Previewing the dataset
print(medical_df.head())

# Selecting the sample 
medical_sample = medical_df.sample(n = 10, replace="False")
print(medical_sample)

(110527, 14)
      PatientId  AppointmentID Gender          ScheduledDay  \
0  2.987250e+13        5642903      F  2016-04-29T18:38:08Z   
1  5.589978e+14        5642503      M  2016-04-29T16:08:27Z   
2  4.262962e+12        5642549      F  2016-04-29T16:19:04Z   
3  8.679512e+11        5642828      F  2016-04-29T17:29:31Z   
4  8.841186e+12        5642494      F  2016-04-29T16:07:23Z   

         AppointmentDay  Age      Neighbourhood  Scholarship  Hipertension  \
0  2016-04-29T00:00:00Z   62    JARDIM DA PENHA            0             1   
1  2016-04-29T00:00:00Z   56    JARDIM DA PENHA            0             0   
2  2016-04-29T00:00:00Z   62      MATA DA PRAIA            0             0   
3  2016-04-29T00:00:00Z    8  PONTAL DE CAMBURI            0             0   
4  2016-04-29T00:00:00Z   56    JARDIM DA PENHA            0             1   

   Diabetes  Alcoholism  Handcap  SMS_received No-show  
0         0           0        0             0      No  
1         0           0  

### <font color="green">6.0 Challenges </font>

In [ ]:
# Challenge 1
# ---
# Select a random sample of 10 from the given dataset below 
# ---
# Dataset url = http://bit.ly/DSRussianInvestigation
# ---
#
Russian_investigation = pd.read_csv("http://bit.ly/DSRussianInvestigation")
#Determining the size
Russian_investigation.shape
#selectong sample
Russia = Russian_investigation.sample(n = 10, replace="False")
Russia

investigation investigation-start investigation-end  investigation-days  \
77         deaver          1986-05-29        1989-08-16                1175   
9       watergate          1973-05-19        1977-06-19                1492   
143          espy          1994-09-09        2001-01-30                2335   
89    iran-contra          1986-12-19        1993-08-03                2419   
101        pierce          1990-03-01        1998-10-27                3162   
29      watergate          1973-05-19        1977-06-19                1492   
100        pierce          1990-03-01        1998-10-27                3162   
133    whitewater          1994-08-05        2002-03-06                2770   
49      watergate          1973-05-19        1977-06-19                1492   
77         deaver          1986-05-29        1989-08-16                1175   

                  name  indictment-days          type     cp-date  cp-days  \
77      Michael Deaver             293.0   conviction  1987-12-16    566.0   
9       E. Howard Hunt            -246.0  guilty-plea  1973-01-11   -128.0   
143    Richard Douglas             769.0  guilty-plea  1998-03-16   1284.0   
89     Clair E. George            1722.0   conviction  1992-12-10   2183.0   
101      Thomas Demery             831.0  guilty-plea  1993-06-17   1204.0   
29   William W. Keeler             199.0  guilty-plea  1973-12-04    199.0   
100  Deborah Gore Dean             789.0   conviction  1993-10-26   1335.0   
133    Charles C. Owen            1364.0   indictment         NaN      NaN   
49       David L. Parr             430.0  guilty-plea  1974-07-23    430.0   
77      Michael Deaver             293.0   conviction  1987-12-16    566.0   

     overturned  pardoned  american         president  
77        False     False      True     Ronald Reagan  
9         False     False      True     Richard Nixon  
143       False      True      True      Bill Clinton  
89        False      True      True     Ronald Reagan  
101       False     False      True  George H.W. Bush  
29        False     False      True     Richard Nixon  
100       False     False      True  George H.W. Bush  
133       False     False      True      Bill Clinton  
49        False      True      True     Richard Nixon  
77        False     False      True     Ronald Reagan

In [ ]:
# Challenge 2
# ---
# A medical company would like to follow up with 50 patients who never showed up for appointments 
# but received an sms. Select a random sample from such patients given the medical dataset below 
# ---
# Dataset url = http://bit.ly/MedicalAppointmentsDataset
# ---
#
medical_df.head(5)

PatientId  AppointmentID Gender          ScheduledDay  \
0  2.987250e+13        5642903      F  2016-04-29T18:38:08Z   
1  5.589978e+14        5642503      M  2016-04-29T16:08:27Z   
2  4.262962e+12        5642549      F  2016-04-29T16:19:04Z   
3  8.679512e+11        5642828      F  2016-04-29T17:29:31Z   
4  8.841186e+12        5642494      F  2016-04-29T16:07:23Z   

         AppointmentDay  Age      Neighbourhood  Scholarship  Hipertension  \
0  2016-04-29T00:00:00Z   62    JARDIM DA PENHA            0             1   
1  2016-04-29T00:00:00Z   56    JARDIM DA PENHA            0             0   
2  2016-04-29T00:00:00Z   62      MATA DA PRAIA            0             0   
3  2016-04-29T00:00:00Z    8  PONTAL DE CAMBURI            0             0   
4  2016-04-29T00:00:00Z   56    JARDIM DA PENHA            0             1   

   Diabetes  Alcoholism  Handcap  SMS_received No-show  
0         0           0        0             0      No  
1         0           0        0             0      No  
2         0           0        0             0      No  
3         0           0        0             0      No  
4         1           0        0             0      No

In [ ]:
medical_df['SMS_received']

0         0
1         0
2         0
3         0
4         0
         ..
110522    1
110523    1
110524    1
110525    1
110526    1
Name: SMS_received, Length: 110527, dtype: int64

In [ ]:
#grouping
med_appointment = medical_df.groupby['SMS_received'].max